In [1]:
#naive bayes
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#load the iris dataset
iris=datasets.load_iris()
X=iris.data
y=iris.target
#split the data into training and testing sets(80% training,20% testing)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#create a Gaussian Naive Bayes classifier
nb_classifier=GaussianNB()

#Train the classifier using the train data
nb_classifier.fit(X_train,y_train)

#make predictions on the testing data
y_pred=nb_classifier.predict(X_test)

#calculate the accuracy of the classifier
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 100.00%


In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris

In [15]:
x, y = load_iris(return_X_y=True)

In [16]:
pd.DataFrame(X)

,0,1,2,3
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.40)

In [21]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

In [22]:
result = confusion_matrix(y_test, y_pred)
print("confusion matrix")
print(result)

confusion matrix
[[17  0  0]
 [ 0 20  0]
 [ 0  2 21]]


In [23]:
result2 = classification_report(y_test, y_pred)
print("classification_report")
print(result2)

classification_report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.91      1.00      0.95        20
           2       1.00      0.91      0.95        23

    accuracy                           0.97        60
   macro avg       0.97      0.97      0.97        60
weighted avg       0.97      0.97      0.97        60



In [26]:
result3 = accuracy_score(y_test, y_pred)
print("accuracy")
print(result3*100)

accuracy
96.66666666666667
