In [4]:
from hi import sum
sum()


9


In [8]:
import numpy as np
a=np.array((1,2,3,4))
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [1]:
import numpy as np
x=np.array([[1,2],[4,5]])
y=np.array([[7,8],[9,10]])
print(x)
print(y)
print("\nThe element wise addition of matrix is :")
print(np.add(x,y))
print("\nThe element wise subtraction of matrix is :")
print(np.subtract(x,y))
print("\nThe element wise division of matrix is :")
print(np.divide(x,y))
print("\nThe element wise multiplication of matrix is :")
print(np.multiply(x,y))

[[1 2]
 [4 5]]
[[ 7  8]
 [ 9 10]]

The element wise addition of matrix is :
[[ 8 10]
 [13 15]]

The element wise subtraction of matrix is :
[[-6 -6]
 [-5 -5]]

The element wise division of matrix is :
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]

The element wise multiplication of matrix is :
[[ 7 16]
 [36 50]]


IndentationError: unexpected indent (Temp/ipykernel_7096/2635246538.py, line 3)